### ISSUE TITLE
Add php-parallel-lint to the PHP linting CI job

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/gha-run-tests#21]
We use PHP Code Sniffer, but that’s not a linter. Notably, it won’t pick up on syntax errors.

We should add https://github.com/php-parallel-lint/PHP-Parallel-Lint to CI to help avoid syntax errors from sneaking in.

## Notes
- We should probably also add this to the testing recipe so that it's included in installer and sink installations by default as a dev dependency, which facilitates running it locally.

## Acceptance criteria
- [x] All supported modules have a php linting step that runs php-parallel-lint
- [x] The linter is run against all source code, tests, and `_config.php` if one exists

## PRs
- https://github.com/silverstripe/gha-run-tests/pull/30
- https://github.com/silverstripe/recipe-testing/pull/22

**Comment by maxime-rainville** [comment]
If we had a syntax error, I would expect PHPUnit to start failing. I can't remember any time where our we had a syntax error that manage to sneak through this way.

Not necessarily against this, but it seems like a very marginal improvement.

**Comment by ChloeSartorelli** [comment]
It is absolutely a very marginal improvement. It's also very little work. IMO seems worth doing.
